package com.admin.ac.ding.model;

import javax.persistence.*;

@Table(name = "`ding_notify_filter`")
public class DingNotifyFilter extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ding_notify_filter.user_id
     *
     * @mbg.generated Sat Sep 15 23:37:51 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ding_notify_filter.user_id
     *
     * @return the value of ding_notify_filter.user_id
     *
     * @mbg.generated Sat Sep 15 23:37:51 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ding_notify_filter.user_id
     *
     * @param userId the value for ding_notify_filter.user_id
     *
     * @mbg.generated Sat Sep 15 23:37:51 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}