package com.admin.ac.ding.model;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`meeting_book`")
public class MeetingBook extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.book_day
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Date bookDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.book_time
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String bookTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.book_user_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String bookUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.meeting_room_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Long meetingRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.meeting_start
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Date meetingStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.meeting_participant_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Integer meetingParticipantCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.meeting_chairman_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Integer meetingChairmanCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.meeting_microphone_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Integer meetingMicrophoneCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.meeting_name
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String meetingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.major_leaders
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String majorLeaders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.use_conditioner
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Byte useConditioner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.use_banner
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Byte useBanner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.use_projector
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Byte useProjector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.book_comment
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String bookComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_book.book_status
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String bookStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.book_day
     *
     * @return the value of meeting_book.book_day
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Date getBookDay() {
        return bookDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.book_day
     *
     * @param bookDay the value for meeting_book.book_day
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setBookDay(Date bookDay) {
        this.bookDay = bookDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.book_time
     *
     * @return the value of meeting_book.book_time
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getBookTime() {
        return bookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.book_time
     *
     * @param bookTime the value for meeting_book.book_time
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setBookTime(String bookTime) {
        this.bookTime = bookTime == null ? null : bookTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.book_user_id
     *
     * @return the value of meeting_book.book_user_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getBookUserId() {
        return bookUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.book_user_id
     *
     * @param bookUserId the value for meeting_book.book_user_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setBookUserId(String bookUserId) {
        this.bookUserId = bookUserId == null ? null : bookUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.meeting_room_id
     *
     * @return the value of meeting_book.meeting_room_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Long getMeetingRoomId() {
        return meetingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.meeting_room_id
     *
     * @param meetingRoomId the value for meeting_book.meeting_room_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMeetingRoomId(Long meetingRoomId) {
        this.meetingRoomId = meetingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.meeting_start
     *
     * @return the value of meeting_book.meeting_start
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Date getMeetingStart() {
        return meetingStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.meeting_start
     *
     * @param meetingStart the value for meeting_book.meeting_start
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMeetingStart(Date meetingStart) {
        this.meetingStart = meetingStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.meeting_participant_count
     *
     * @return the value of meeting_book.meeting_participant_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Integer getMeetingParticipantCount() {
        return meetingParticipantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.meeting_participant_count
     *
     * @param meetingParticipantCount the value for meeting_book.meeting_participant_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMeetingParticipantCount(Integer meetingParticipantCount) {
        this.meetingParticipantCount = meetingParticipantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.meeting_chairman_count
     *
     * @return the value of meeting_book.meeting_chairman_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Integer getMeetingChairmanCount() {
        return meetingChairmanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.meeting_chairman_count
     *
     * @param meetingChairmanCount the value for meeting_book.meeting_chairman_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMeetingChairmanCount(Integer meetingChairmanCount) {
        this.meetingChairmanCount = meetingChairmanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.meeting_microphone_count
     *
     * @return the value of meeting_book.meeting_microphone_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Integer getMeetingMicrophoneCount() {
        return meetingMicrophoneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.meeting_microphone_count
     *
     * @param meetingMicrophoneCount the value for meeting_book.meeting_microphone_count
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMeetingMicrophoneCount(Integer meetingMicrophoneCount) {
        this.meetingMicrophoneCount = meetingMicrophoneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.meeting_name
     *
     * @return the value of meeting_book.meeting_name
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getMeetingName() {
        return meetingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.meeting_name
     *
     * @param meetingName the value for meeting_book.meeting_name
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMeetingName(String meetingName) {
        this.meetingName = meetingName == null ? null : meetingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.major_leaders
     *
     * @return the value of meeting_book.major_leaders
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getMajorLeaders() {
        return majorLeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.major_leaders
     *
     * @param majorLeaders the value for meeting_book.major_leaders
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMajorLeaders(String majorLeaders) {
        this.majorLeaders = majorLeaders == null ? null : majorLeaders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.use_conditioner
     *
     * @return the value of meeting_book.use_conditioner
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Byte getUseConditioner() {
        return useConditioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.use_conditioner
     *
     * @param useConditioner the value for meeting_book.use_conditioner
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setUseConditioner(Byte useConditioner) {
        this.useConditioner = useConditioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.use_banner
     *
     * @return the value of meeting_book.use_banner
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Byte getUseBanner() {
        return useBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.use_banner
     *
     * @param useBanner the value for meeting_book.use_banner
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setUseBanner(Byte useBanner) {
        this.useBanner = useBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.use_projector
     *
     * @return the value of meeting_book.use_projector
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Byte getUseProjector() {
        return useProjector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.use_projector
     *
     * @param useProjector the value for meeting_book.use_projector
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setUseProjector(Byte useProjector) {
        this.useProjector = useProjector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.book_comment
     *
     * @return the value of meeting_book.book_comment
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getBookComment() {
        return bookComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.book_comment
     *
     * @param bookComment the value for meeting_book.book_comment
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setBookComment(String bookComment) {
        this.bookComment = bookComment == null ? null : bookComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_book.book_status
     *
     * @return the value of meeting_book.book_status
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_book.book_status
     *
     * @param bookStatus the value for meeting_book.book_status
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus == null ? null : bookStatus.trim();
    }
}