package com.admin.ac.ding.model;

import javax.persistence.*;

@Table(name = "`meeting_room_detail`")
public class MeetingRoomDetail extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_detail.name
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_detail.place
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_detail.size
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_detail.type
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_detail.memo
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_detail.name
     *
     * @return the value of meeting_room_detail.name
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_detail.name
     *
     * @param name the value for meeting_room_detail.name
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_detail.place
     *
     * @return the value of meeting_room_detail.place
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_detail.place
     *
     * @param place the value for meeting_room_detail.place
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_detail.size
     *
     * @return the value of meeting_room_detail.size
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_detail.size
     *
     * @param size the value for meeting_room_detail.size
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_detail.type
     *
     * @return the value of meeting_room_detail.type
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_detail.type
     *
     * @param type the value for meeting_room_detail.type
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_detail.memo
     *
     * @return the value of meeting_room_detail.memo
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_detail.memo
     *
     * @param memo the value for meeting_room_detail.memo
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}