package com.admin.ac.ding.model;

import javax.persistence.*;

@Table(name = "`privileged_dept`")
public class PrivilegedDept extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privileged_dept.dept_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    private Long deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privileged_dept.dept_id
     *
     * @return the value of privileged_dept.dept_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privileged_dept.dept_id
     *
     * @param deptId the value for privileged_dept.dept_id
     *
     * @mbg.generated Sun Aug 12 21:21:39 CST 2018
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }
}