package com.admin.ac.ding.model;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`suggest_manage`")
public class SuggestManage extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.user_id
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.status
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.process_user_id
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private String processUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.gmt_relay
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private Date gmtRelay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.gmt_process
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private Date gmtProcess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.suggest
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private String suggest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.pics
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private String pics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.relay_comment
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private String relayComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggest_manage.process_comment
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    private String processComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.user_id
     *
     * @return the value of suggest_manage.user_id
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.user_id
     *
     * @param userId the value for suggest_manage.user_id
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.status
     *
     * @return the value of suggest_manage.status
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.status
     *
     * @param status the value for suggest_manage.status
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.process_user_id
     *
     * @return the value of suggest_manage.process_user_id
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public String getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.process_user_id
     *
     * @param processUserId the value for suggest_manage.process_user_id
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setProcessUserId(String processUserId) {
        this.processUserId = processUserId == null ? null : processUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.gmt_relay
     *
     * @return the value of suggest_manage.gmt_relay
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public Date getGmtRelay() {
        return gmtRelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.gmt_relay
     *
     * @param gmtRelay the value for suggest_manage.gmt_relay
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setGmtRelay(Date gmtRelay) {
        this.gmtRelay = gmtRelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.gmt_process
     *
     * @return the value of suggest_manage.gmt_process
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public Date getGmtProcess() {
        return gmtProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.gmt_process
     *
     * @param gmtProcess the value for suggest_manage.gmt_process
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setGmtProcess(Date gmtProcess) {
        this.gmtProcess = gmtProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.suggest
     *
     * @return the value of suggest_manage.suggest
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.suggest
     *
     * @param suggest the value for suggest_manage.suggest
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest == null ? null : suggest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.pics
     *
     * @return the value of suggest_manage.pics
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.pics
     *
     * @param pics the value for suggest_manage.pics
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.relay_comment
     *
     * @return the value of suggest_manage.relay_comment
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public String getRelayComment() {
        return relayComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.relay_comment
     *
     * @param relayComment the value for suggest_manage.relay_comment
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setRelayComment(String relayComment) {
        this.relayComment = relayComment == null ? null : relayComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggest_manage.process_comment
     *
     * @return the value of suggest_manage.process_comment
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public String getProcessComment() {
        return processComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggest_manage.process_comment
     *
     * @param processComment the value for suggest_manage.process_comment
     *
     * @mbg.generated Thu Aug 30 23:08:26 CST 2018
     */
    public void setProcessComment(String processComment) {
        this.processComment = processComment == null ? null : processComment.trim();
    }
}